### ISSUE TITLE
[Feature Request] allow user-definable wandb run id to deal with cluster pre-emption/timeouts

### ISSUE THREAD

**Issue by tesfaldet** [captain-pool/hydra-wandb-sweeper#1]
# 🚀 Feature Request

https://github.com/captain-pool/hydra-wandb-sweeper/blob/60fa6d531e58cb3a46b4f14648d47ed7608df589/hydra_plugins/hydra_wandb_sweeper/wandb_sweeper.py#L160-L173

Currently (as far as I see in the code, I haven't actually verified this), if an agent or multiple agents running on a cluster node (e.g., under a SLURM job) experiences preemption or timeout, when the job is requeued (through Hydra's submitit launcher, for example) then the agent(s) can not resume its run and instead creates a new one every time `wandb_task` is called by the launcher.

## Motivation
Having the wandb run id be user-definable can allow for the user to pass in, for example, a run id that's the same as the SLURM job ID. Based on how Hydra's submitit plugin works, when its `checkpoint` function is called upon preemption/timeout, it requeues the job with the same job ID and initial configuration. By having this job ID be used for the wandb run id for the agent that got preempted/timed-out, the wandb run can also be resumed when the job is resumed.

**Comment by captain-pool** [comment]
Awesome! Thanks for the input @tesfaldet I'll look in it.

**Comment by captain-pool** [comment]
Asked around and found out it's not possible to pass custom run id to a sweep agent to resume that sweep. However, there's a wandb way of resume sweep runs after preemption: https://docs.wandb.ai/guides/track/advanced/resuming#preemptible-sweeps

Just merged a pull request with the same https://github.com/captain-pool/hydra-wandb-sweeper/pull/2

Lmk if this works. Thanks for pointing it out!

**Comment by tesfaldet** [comment]
Hahaha yeah I just learned of that the other day too! I was gonna post here but forgot :/ I totally forgot about `wandb.mark_preempting()`

**Comment by captain-pool** [comment]
I'm closing this issue for now, please feel free to open it if there's anything else.
