### ISSUE TITLE
Multiple run_id

### ISSUE THREAD

**Issue by d-miketa** [captain-pool/hydra-wandb-sweeper#6]
Hi, 

Thanks for the plugin! I'm super interested in trying it out.

I'd like to run something like the following:

```python
@hydra.main(...)
def cli(cfg: DictConfig, ...):
  with wandb.init(job_type="train", ...):
    train_model()

  with wandb.init(job_type="benchmark", ...):
    benchmark_model()
```
but the current interface requires that I pass a single run_id to W&B run definitions. Since I'm triggering two runs, I need two IDs. Is there a way around this limitation?

**Comment by captain-pool** [comment]
Hi @d-miketa thanks for your interest. Don’t think you can do that. that’s because each hydra `TaskFunction` (here `cli(…)` )is being launched by W&B sweeps agent. Since an agent explicitly controls run creation, you cannot do something like this.

*Note*: this plugin is only for using W&B sweeper with Hydra and having the capability to launch parallel runs. If you don't want to have this capabilty, I wrote an extensive report on using hydra with W&B: http://wandb.me/hydra. You can probably do something like this with this approach. For reference please feel free to checkout the minimal example on using hydra with W&B: http://wandb.me/hydra-minimal-example. Let me know if you have any questions.

**Comment by d-miketa** [comment]
I've seen the report, many thanks for authoring it!

But I don't want to give up on this just yet. What would happen if I pass the `run_id` to `train` but not to `benchmark`? W&B starts the first run "behind the scenes" (as I understand from your discussion in https://github.com/captain-pool/hydra-wandb-sweeper/pull/5), then the `wandb.init(id=run_id, job_type="train")` context hooks into the original run and eventually concludes it. What happens if I then start another run with `wandb.init(job_type="benchmark")`? Should work just fine, no?

**Comment by captain-pool** [comment]
Hmm, don't think so. All of them would log in the same run. I found out this later that it doesn't matter if we pass a `run_id` or not, if you invoke `wandb.init(...)` inside an agent, it will automatically capture the run the agent created. So, the run_id thing is pretty redundant. (this happens even if the `wandb.init(...)` is not being called from inside a parent context).

**Comment by d-miketa** [comment]
Isn't this schematically what's happening though?

```python
wandb.init(...)  # agent initialises a run

# then the user attempts to start another run but in reality just hooks to the one started earlier
with wandb.init(...) as run:
  ...
```

At the end of that context, the manager executes `run.finish()` and automatically shuts down the W&B run. So the next context manager has no pre-existing run to hook into and starts a genuine new one... I think?

**Comment by captain-pool** [comment]
Well, sadly, that doesn't happen. While performing sweeps, only an agent can create a new run. :/ Would be amazing to have this feature in W&B, but as of now, that doesn't happen. Even if you close the last run, the new wandb.init() tries to continue the last run.

So even something like this:
```
run = wandb.init(...)
....
run.finish()
run = wandb.init(...)
....
run.finish()
```
won't create two different runs if this code is inside an agent.

**Comment by d-miketa** [comment]
Argh, that's unfortunate. Anything I can do to flag with you guys that it'd be a useful feature?

**Comment by captain-pool** [comment]
I raised a ticket internally. Thanks for pointing this out 😄  I'm closing the issue for now. Please feel free to open it, if there's anything else.

**Comment by tesfaldet** [comment]
This is an interesting request as it raises some questions I'd like to ask to the folks at W&B (I'll leave that for later).

@d-miketa your use case seems better suited for outside the Hydra sweep interface as @captain-pool noted:
> Note: this plugin is only for using W&B sweeper with Hydra and having the capability to launch parallel runs. If you don't want to have this capabilty, I wrote an extensive report on using hydra with W&B: http://wandb.me/hydra. You can probably do something like this with this approach. For reference please feel free to checkout the minimal example on using hydra with W&B: http://wandb.me/hydra-minimal-example. Let me know if you have any questions.

If you still want to use the Hydra sweeper, perhaps I can help out? What sort of benchmarking are you doing? Is it validation on a held out set? If so, you can always log those metrics separately within the same run `train/loss` vs `validation/loss`.

**Comment by d-miketa** [comment]
I decided to indeed take benchmarking out of that interface. My original intention was to (at least have the flexibility to) range over several evaluation datasets per each trained model, but tangling training and benchmarking in the same Hydra CLI proved too cumbersome to be worth it.
